export const booksData = [
	{
		author: {
			first_name: 'Emily',
			last_name: 'Bronte',
			middle_name: '',
		},
		_id: '652bb854ae3079c307c4e649',
		book_id: 9,
		title: 'The Complete Poems of Emily Bronte',
		pages: 80,
		genres: [
			'Poetry',
			'Classics',
			'Victorian',
			'Fiction',
			'English Literature',
		],
		rating: 4.17,
		plot: 'The Complete Poems Of Emily Bronte is a collection of all the poems written by the famous English novelist and poet, Emily Bronte. Published in 1908, this book features a comprehensive collection of her poetic works, including both published and unpublished poems. Emily Bronte is known for her powerful and evocative writing style, and her poetry is no exception. Her works explore themes of nature, love, death, and the human experience, and are marked by their emotional intensity and vivid imagery. The poems included in this collection offer a glimpse into the mind of one of the greatest literary figures of the 19th century, and showcase the breadth and depth of her poetic talent. As a result, The Complete Poems Of Emily Bronte is a must-read for anyone interested in English literature, poetry, or the works of Emily Bronte.',
		reviews: {
			name: 'Lucy',
			body: "If I could rate this one billion stars, I would. These poems are incredibly precious to me - they've been with me throughout the bad times and the good, ever-present in my life.There's not a lot I wouldn't do to somehow turn back time and rescue the rest of the Gondal work.",
		},
		cover: 'https://cdn2.penguin.com.au/covers/400/9780141966762.jpg',
		url: 'https://www.amazon.in/Complete-Poems-Penguin-Classics/dp/0140423524/ref=sr_1_1?crid=1ESDY0GQ6NQAF&keywords=The+Complete+Poems+Emily+Bront%C3%AB&qid=1697358155&sprefix=the+complete+poems+emily+bront%C3%AB%2Caps%2C198&sr=8-1',
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Lee',
			body: "Dickens was one of the best character writers in literary history. Oliver Twist is another example of his palpable skill. With standouts like Fagin, the artful dodger, Charlie Bates, Mr. Bumble, Bill Sikes and Oliver Twist himself Dickens weaves a story of lost inheritance at the hands of London's criminal network. there is a mystery here that the great dickens leave to the end. Of course, with Dickens he takes a while getting there using his patented florid descriptive language. You have to be ok with descriptive dialogue to enjoy his work. I shudder to think of his longer works like Bleak House or Nicholas Nickleby since even in this and Great expectations Dickens can meander into side stories for many chapters. You probably know a little of Oliver's story but do you know his family history if not read this and let the master storyteller enthrall you.",
		},
		_id: '653fc96abcb135ac0922a0dc',
		book_id: 13,
		title: 'Oliver Twist',
		pages: 608,
		genres: ['Classics', 'Fiction', 'Literature', 'Novels', 'Historic fiction'],
		rating: 3.88,
		plot: "The story of Oliver Twist - orphaned, and set upon by evil and adversity from his first breath - shocked readers when it was published. After running away from the workhouse and pompous beadle Mr Bumble, Oliver finds himself lured into a den of thieves peopled by vivid and memorable characters - the Artful Dodger, vicious burglar Bill Sikes, his dog Bull's Eye, and prostitute Nancy, all watched over by cunning master-thief Fagin. Combining elements of Gothic Romance, the Newgate Novel and popular melodrama, Dickens created an entirely new kind of fiction, scathing in its indictment of a cruel society, and pervaded by an unforgettable sense of threat and mystery.",
		cover:
			'https://pathakshamabesh.com/wp-content/uploads/2020/07/71K4SkM3IRL-600x931.jpg',
		url: 'https://www.amazon.in/OLIVER-TWIST-Charles-Dickens/dp/8175993707/ref=sr_1_2_sspa?crid=1RNYXCYIR889Z&keywords=oliver+twist+charles+dickens&qid=1698677548&sprefix=oliver+%2Caps%2C243&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
		__v: 0,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b906a2abbe49eef43665f',
		book_id: 2,
		title: 'Pride and Prejudice',
		pages: 432,
		genres: ['Romance', 'Fiction', 'Classics'],
		rating: 4.5,
		plot: "Set in England in the early 19th century, Pride and Prejudice tells the story of Mr and Mrs Bennet's five unmarried daughters after the rich and eligible Mr Bingley and his status-conscious friend, Mr Darcy, have moved into their neighbourhood. While Bingley takes an immediate liking to the eldest Bennet daughter, Jane, Darcy has difficulty adapting to local society and repeatedly clashes with the second-eldest Bennet daughter, Elizabeth.",
		reviews: {
			name: 'bookanalysis.com',
			body: "Pride and Prejudice is a novel of all the time. It has captivated the hearts of readers across ages. The interesting plot captures the reader's attention from the very first line. As it is narrated through the perspective of Elizabeth Bennet, the readers will get the feel of living alongside the Bennet family. As Elizabeth undergoes a change in perspective and character, readers get a picture of the other characters present in the novel and the time of the novel.One could understand the novel well in the very first reading. Though young readers of the present may find it difficult to understand the plot in a certain part, yet, close reading and a background knowledge of Austen's time will help one understand the novel better and enjoy.",
		},
		cover: 'https://images.thenile.io/r1000/9780141439518.jpg',
		url: 'https://www.amazon.in/Pride-Prejudice-Penguin-Classics-Austen/dp/0141439513/ref=sr_1_6?crid=18J1DS2F3G0R&keywords=Pride+and+Prejudice&qid=1697353631&sprefix=pride+and+prejudice%2Caps%2C212&sr=8-6',
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Luis',
			body: '"Dombey and Son" is not Charles Dickens\'s best-known novel, far from it. However, its thousand pages contain a lovely family and social fiction that his contemporary Victor Hugo will doubtless not have disdained. All the ingredients make a Dickensian novel an extraordinary universe of shattered destinies and colorful figures.\nA novel of vanity and ambition, "Dombey & Son" denounces the greed of the heart, the pretension of class, the manipulation of beings, and the harshness of a society that does not spare those in need. With unique humor, Charles Dickens deploys this talent that belongs only to him to give life to a massive gallery of characters to eat in both senses.\nI don\'t know of any other period author capable of featuring many leading and supporting characters, nimbly interlocking them with each other, and giving them a personality of their own, endearing or repulsive. Likewise, each actor in this beautiful drama searched and worked in-depth until he offered the reader the best of his qualities or faults. The result is such a closeness to the ordinary heroes and heroines of the novel that we, the readers, feel ourselves becoming one of them.',
		},
		_id: '6549f2c5bb6ef54f8f7d8ec5',
		book_id: 23,
		title: 'Dombey and Son',
		pages: 880,
		genres: [
			'Classics',
			'Historical',
			'Literature',
			'Historical fiction',
			'Fiction',
			'19th Century',
			'Victorian',
		],
		rating: 3.95,
		plot: 'Dombey and Son, a novel by English author Charles Dickens, delves into the fortunes of a shipping firm owner named Paul Dombey. His fervent desire is to have a son who can carry on his business legacy. However, when his son is born, tragedy strikes as his wife passes away shortly after childbirth. The grieving Dombey neglects his daughter, Florence, who yearns for her father’s love.\nThe story unfolds with a series of Dickensian themes: arranged marriages, child cruelty, betrayal, deceit, and the complex relations between people from different British social classes.',
		cover:
			'https://th.bing.com/th/id/OIP.Gt40EpJRLnrDSGGcK4ihFwHaL0?pid=ImgDet&rs=1',
		url: 'https://www.amazon.in/Dombey-Penguin-Classics-Charles-Dickens/dp/0140435468/ref=sr_1_1?crid=KYA2X1C56A3U&keywords=Dombey+and+Son+by+charles+dickens&qid=1699344553&sprefix=dombey+and+son+by+charles+dickens%2Caps%2C202&sr=8-1',
		__v: 0,
	},
];
