export const booksData = [
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b8d86b9ee9bb5d1bbda9b',
		book_id: 1,
		title: 'Sense and Sensibility',
		pages: 368,
		genres: ['Romance', 'Fiction', 'Classics'],
		reviews: {
			name: 'Holly Parker',
			body: "I love the story (though not as much as I love Pride and Prejudice). My only complaint is how old Colonel Brandon is. Justify it all you want with \"it was a different time;\" he is more than twice Marianne's age at the beginning of the book (he's 35, she's 16). He could be her father. Yikes. Otherwise, I love the book and all its dramas and pettiness.",
		},
		cover: 'https://cdn2.penguin.com.au/covers/original/9780375756733.jpg',
		url: 'https://www.amazon.in/Sense-Sensibility-Penguin-Classics-Austen/dp/0141439661/ref=sr_1_3?crid=2HVW537O79PTA&keywords=Sense+and+Sensibility&qid=1697352083&sprefix=sense+and+sensibility%2Caps%2C254&sr=8-3',
		plot: "Abeloved classic, Austen's first published novel explores the question of what drives your life: your heart or your head? The Dashwood sisters, Elinor and Marianne, are as different as sisters can be. Serious Elinor lives by reason and thoughtfulness while her younger sister, Marianne, only follows her passions. But in questions of love, they learn neither the heart nor head alone will lead them to happiness. Filled with romance, Austen's brilliant wit, and rich characterization, this is a celebration of sisterly love and the need for family--no matter how different they might be from us.",
		rating: 4.3,
		price: 212,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b906a2abbe49eef43665f',
		book_id: 2,
		title: 'Pride and Prejudice',
		pages: 432,
		genres: ['Romance', 'Fiction', 'Classics'],
		rating: 4.5,
		plot: "Set in England in the early 19th century, Pride and Prejudice tells the story of Mr and Mrs Bennet's five unmarried daughters after the rich and eligible Mr Bingley and his status-conscious friend, Mr Darcy, have moved into their neighbourhood. While Bingley takes an immediate liking to the eldest Bennet daughter, Jane, Darcy has difficulty adapting to local society and repeatedly clashes with the second-eldest Bennet daughter, Elizabeth.",
		reviews: {
			name: 'bookanalysis.com',
			body: "Pride and Prejudice is a novel of all the time. It has captivated the hearts of readers across ages. The interesting plot captures the reader's attention from the very first line. As it is narrated through the perspective of Elizabeth Bennet, the readers will get the feel of living alongside the Bennet family. As Elizabeth undergoes a change in perspective and character, readers get a picture of the other characters present in the novel and the time of the novel.One could understand the novel well in the very first reading. Though young readers of the present may find it difficult to understand the plot in a certain part, yet, close reading and a background knowledge of Austen's time will help one understand the novel better and enjoy.",
		},
		cover: 'https://images.thenile.io/r1000/9780141439518.jpg',
		url: 'https://www.amazon.in/Pride-Prejudice-Penguin-Classics-Austen/dp/0141439513/ref=sr_1_6?crid=18J1DS2F3G0R&keywords=Pride+and+Prejudice&qid=1697353631&sprefix=pride+and+prejudice%2Caps%2C212&sr=8-6',
		price: 248,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b9744ae3079c307c4e643',
		book_id: 3,
		title: 'Mansfield Park',
		pages: 560,
		genres: ['Romance', 'Fiction', 'Classics'],
		rating: 3.86,
		plot: "The eldest of nine children born to a naval lieutenant with a meager pension, Fanny Price is sent to live with wealthy relatives at Mansfield Park. Only ten years old, she is nervous around her rich cousins and uncomfortable in their grand house. And as the years pass, Fanny comes to believe that she will never truly feel at home. Only Edmund Bertram makes life worth living.He is the only one of her cousins who is kind to her, a gentle soul whom she has loved since childhood. But when the worldly and charismatic Crawford siblings, Henry and Mary, arrive from London and ensnare the Bertram family in a complicated web of romance and intrigue, Fanny worries that her relationship with Edmund will never be the same. To win his heart, she must keep her head—a task that becomes all the more difficult when her family pressures her to accept Henry Crawford's unexpected marriage proposal.",
		reviews: {
			name: 'anonymous',
			body: "Complex, yet very good. Shows how rigid the class (and race) systems were entrenched in English society then and still persists to some extent today. Also shows the addiction to Laudanum, an opium based drug used commonly among the upper classes; even Queen Victoria was rumored to partake of the drug on occasion! The lower classes were addicted to gin; the main character's father was an unemployed alcoholic with too many children; his wife had definitely married downward; hence the the thread that runs through the story. A good read (and film) nonetheless. I enjoyed the book more than the film, though.",
		},
		cover:
			'https://d28hgpri8am2if.cloudfront.net/book_images/cvr9781439169438_9781439169438_hr.jpg',
		url: 'https://www.amazon.in/Mansfield-Park-Jane-Austen/dp/8172345232/ref=sr_1_1?crid=1TWPOKVS2OXZ&keywords=Mansfield+Park&qid=1697355117&sprefix=mansfield+park%2Caps%2C236&sr=8-1',
		price: 195,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b9c09ae3079c307c4e644',
		book_id: 4,
		title: 'Emma',
		pages: 512,
		genres: ['Romance', 'Fiction', 'Classics'],
		rating: 4.04,
		plot: " 'Emma' by Jane Austen is a classic novel that revolves around the life of Emma Woodhouse, a young and wealthy woman living in Highbury, England. Emma, who fancies herself a skilled matchmaker, takes it upon herself to meddle in the romantic lives of her friends and acquaintances. She tries to pair people up but often misinterprets their feelings and intentions, leading to humorous and sometimes complicated situations. Throughout the story, Emma learns valuable lessons about love and self-awareness.",
		reviews: {
			name: 'Adam',
			body: "Oh my goodness, did I love. At one point, toward the end, when the thing that Austen was working toward happened, I literally fell down from the couch to the rug. Emma herself is a unique creation, a headstrong, misguided, self-confident girl who we can't help but love, because she is honest. The love complications are innumerable, the humor is excellent, and the writing is spectacular. Without the intensely crafted plot of Pride and Prejudice, say, Austen's sentences are left to carry the book, something that they are more than capable of. It was interesting to read this in concert with Dostoyevsky's THE IDIOT, because they have much in common, and because there is as much truth and insight here, with additional pleasures. Austen is habitually underrated for the usual reasons, and also because the adaptations of her work showcase her facility with plot more than language. On the page, one wants to read her fast, but one also wants to linger in the prose.",
		},
		cover: 'https://i.thenile.io/r1000/9781514758397.jpg?r=60a26e5e6f5ef',
		url: 'https://www.amazon.in/EMMA-FingerPrint-Jane-Austen/dp/8172345305/ref=sr_1_1_sspa?crid=TDRQXQPSADPD&keywords=Emma+book&qid=1697356145&sprefix=emma+book%2Caps%2C204&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
		price: 219,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b9c09ae3079c307c4e645',
		book_id: 5,
		title: 'Northanger Abbey',
		pages: 288,
		genres: ['Romance', 'Fiction', 'Classics', 'Gothic fiction'],
		rating: 3.84,
		plot: "'Northanger Abbey' by Jane Austen is a novel that follows the adventures of Catherine Morland, a young and imaginative woman from the countryside who is invited to visit the fashionable spa town of Bath. Catherine becomes enamored with Gothic novels and lets her imagination run wild. She is invited to stay at Northanger Abbey, a mysterious and ancient estate, and begins to imagine dark secrets and mysteries. The novel humorously explores the contrast between Catherine's overactive imagination and the reality of her experiences in society, love, and friendship.",
		reviews: {
			name: 'Julian',
			body: "Northanger Abbey tells the tale of Catherine Morland who leaves her sheltered, rural life for a few weeks to visit the busy, sophisticated world of Bath.I thought this book ended a little quickly.I would like to have known what happened to Isabella and James Morland, Catherine's brother. I was intrigued by Isabella and wanted to learn what her true intentions were, but the ending left me hanging.",
		},
		cover:
			'https://i.pinimg.com/originals/7b/b6/6a/7bb66a03364eddc5811d71af8900f5c9.jpg',
		url: 'https://www.amazon.in/Northanger-Abbey-Jane-Austen/dp/9350330768/ref=sr_1_3?crid=3C73Q3Q9Y4PD6&keywords=Northanger+Abbey&qid=1697356307&sprefix=northanger+abbey%2Caps%2C242&sr=8-3',
		price: 152,
	},
	{
		author: {
			first_name: 'Jane',
			last_name: 'Austen',
			middle_name: '',
		},
		_id: '652b9c09ae3079c307c4e646',
		book_id: 6,
		title: 'Persuasion',
		pages: 304,
		genres: ['Romance', 'Fiction', 'Classics', 'Literature', 'Historical'],
		rating: 4.15,
		plot: "'Persuasion' by Jane Austen tells the story of Anne Elliot, a woman who is persuaded by her family to break off her engagement with the love of her life, Captain Frederick Wentworth. Eight years later, they meet again, and Anne must navigate her feelings and societal expectations. The novel explores themes of second chances, love, and the consequences of persuasion.",
		reviews: {
			name: 'Tadiana',
			body: "Austen's intelligence, dry wit and humor are evidenced on every page. The melancholy, autumnal feel of the first part of the book, when all you can see is Anne's blighted hopes and how she is disregarded and mistreated by almost everyone around her, is wrenching. Then, like springtime, comes the slow, gradual return of joy and hope to Anne's life.",
		},
		cover:
			'https://imgv2-1-f.scribdassets.com/img/word_document/251891585/original/7e43197740/1615480324?v=1',
		url: 'https://www.amazon.in/Persuasion-Jane-Austen/dp/8175993790/ref=sr_1_4?crid=2FC0QG286C2WO&keywords=Persuasion&qid=1697356518&sprefix=persuasion%2Caps%2C217&sr=8-4',
		price: 129,
	},
	{
		author: {
			first_name: 'Charlotte',
			last_name: 'Bronte',
			middle_name: '',
		},
		_id: '652bb854ae3079c307c4e648',
		book_id: 7,
		title: 'Jane Eyre',
		pages: 1696,
		genres: ['Fiction', 'Classics', 'Romance', 'Gothic', 'Historical'],
		rating: 4.14,
		plot: "Charlotte Brontë tells the story of orphaned Jane Eyre, who grows up in the home of her heartless aunt, enduring loneliness and cruelty. This troubled childhood strengthens Jane's natural independence and spirit - which prove necessary when she finds employment as a governess to the young ward of Byronic, brooding Mr Rochester. As her feelings for Rochester develop, Jane gradually uncovers Thornfield Hall's terrible secret, forcing her to make a choice. Should she stay with Rochester and live with the consequences, or follow her convictions - even if it means leaving the man she loves? A novel of intense power and intrigue, Jane Eyre dazzled readers with its passionate depiction of a woman's search for equality and freedom.",
		reviews: {
			name: 'Dana',
			body: "For years I've been saying that Jane Eyre is my favorite novel of all time-- and that it is. The character of Jane is, to me, one of the most admirable and appealing fictional characters of all time. Poor and plain she may be, but her spirit is indomitable.In an era when women were expected to be brainless and ornamental, Jane (through the words of Charlotte Bronte) refused to bow to those expectations.",
		},
		cover:
			'https://s2982.pcdn.co/wp-content/uploads/2016/09/Penguin-Classics.jpg',
		url: 'https://www.amazon.in/Jane-Penguin-Classics-Charlotte-Bront%C3%AB/dp/0141441143/ref=sr_1_3?crid=1LXTKURDPEZGW&keywords=Jane+Eyre&qid=1697357960&sprefix=jane+eyre%2Caps%2C202&sr=8-3',
		price: 299,
	},
	{
		author: {
			first_name: 'Emily',
			last_name: 'Bronte',
			middle_name: '',
		},
		_id: '652bb854ae3079c307c4e649',
		book_id: 8,
		title: 'The Complete Poems of Emily Bronte',
		pages: 80,
		genres: [
			'Poetry',
			'Classics',
			'Victorian',
			'Fiction',
			'English Literature',
		],
		rating: 4.17,
		plot: 'The Complete Poems Of Emily Bronte is a collection of all the poems written by the famous English novelist and poet, Emily Bronte. Published in 1908, this book features a comprehensive collection of her poetic works, including both published and unpublished poems. Emily Bronte is known for her powerful and evocative writing style, and her poetry is no exception. Her works explore themes of nature, love, death, and the human experience, and are marked by their emotional intensity and vivid imagery. The poems included in this collection offer a glimpse into the mind of one of the greatest literary figures of the 19th century, and showcase the breadth and depth of her poetic talent. As a result, The Complete Poems Of Emily Bronte is a must-read for anyone interested in English literature, poetry, or the works of Emily Bronte.',
		reviews: {
			name: 'Lucy',
			body: "If I could rate this one billion stars, I would. These poems are incredibly precious to me - they've been with me throughout the bad times and the good, ever-present in my life.There's not a lot I wouldn't do to somehow turn back time and rescue the rest of the Gondal work.",
		},
		cover: 'https://cdn2.penguin.com.au/covers/400/9780141966762.jpg',
		url: 'https://www.amazon.in/Complete-Poems-Penguin-Classics/dp/0140423524/ref=sr_1_1?crid=1ESDY0GQ6NQAF&keywords=The+Complete+Poems+Emily+Bront%C3%AB&qid=1697358155&sprefix=the+complete+poems+emily+bront%C3%AB%2Caps%2C198&sr=8-1',
		price: 545,
	},
	{
		author: {
			first_name: 'Emily',
			last_name: 'Bronte',
			middle_name: '',
		},
		_id: '652bb854ae3079c307c4e64a',
		book_id: 9,
		title: 'The Night is Darkening Round Me',
		pages: 64,
		genres: ['Poetry', 'Classics', 'Gothic'],
		rating: 3.84,
		plot: "Some of Emily Brontë's most extraordinary poems",
		reviews: {
			name: 'Jo',
			body: 'A lovely selection of poetry, though lovely might be the wrong word. Death is a major theme, but I still found them to be lovely in the sense that they evoked imagery of nature that I cannot say is anything but lovely. Very rarely does poetry evoke such imagery with me, but the lower rating comes from the fact that, again, this poetry was very hit-and-miss, as most poetry seems to be.',
		},
		cover: 'https://d.gr-assets.com/books/1423758040l/24874353.jpg',
		url: 'https://www.amazon.in/Night-Darkening-Penguin-Little-Classics/dp/0141398477/ref=sr_1_1?crid=1VIGI15GU445J&keywords=The+Night+is+Darkening+Round+Me&qid=1697358327&sprefix=the+night+is+darkening+round+me%2Caps%2C193&sr=8-1',
		price: 150,
	},
	{
		author: {
			first_name: 'Agatha',
			last_name: 'Christie',
			middle_name: 'Mary',
		},
		_id: '652bc02d2d929d538cdc8026',
		book_id: 10,
		title: 'The Murder of Roger Ackroyd',
		pages: 288,
		genres: [
			'Mystery',
			'Detective fiction',
			'Crime fiction',
			'Classics',
			'Murder Mystery',
		],
		rating: 4.26,
		plot: '“The Murder of Roger Ackroyd” is a detective novel by Agatha Christie. The story is narrated by Dr. James Sheppard, a physician in the small village of King’s Abbot. The novel begins with the suicide of Mrs. Ferrars, a wealthy widow who had been blackmailed for poisoning her husband. The next day, Roger Ackroyd, Mrs. Ferrars’ fiancé, is found murdered in his study. Dr. Sheppard becomes involved in the investigation and helps to solve the mystery.',
		reviews: {
			name: 'Sandie',
			body: 'It was fun to read some Agatha after such a long time. I can certainly see why she is so popular. She is the most widely published author after the Bible and Shakespeare. Her descriptions of people and plotting are well done. Her one paragraph on the sister Caroline is precious. She does have tropes, like always gathering all the suspects together in one room and eliminating them one by one. Also throwing red herrings out at possible suspects. I must say that I did not guess the perpetrator in this book. Glad I read it and our book group had fun with it.',
		},
		cover: 'https://images3.penguinrandomhouse.com/cover/9780593466360',
		url: 'https://www.amazon.in/Murder-Roger-Ackroyd-Agatha-Christie/dp/1684226562/ref=sr_1_1_sspa?keywords=The+Murder+of+Roger+Ackroyd&qid=1697365341&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
		price: 870,
	},
	{
		author: {
			first_name: 'Agatha',
			last_name: 'Christie',
			middle_name: 'Mary',
		},
		_id: '652bc15a588fb26646fb0e59',
		book_id: 12,
		title: 'Murder on the Orient Express',
		pages: 256,
		genres: ['Mystery', 'Crime fiction', 'Detective fiction'],
		rating: 4.2,
		plot: 'Just after midnight, a snowdrift stops the famous Orient Express in its tracks as it travels through the mountainous Balkans. The luxurious train is surprisingly full for the time of the year but, by the morning, it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside.One of the passengers is none other than detective Hercule Poirot. On vacation.Isolated and with a killer on board, Poirot must identify the murderer—in case he or she decides to strike again.',
		reviews: {
			name: 'Annemarie',
			body: 'This was my first, but definitely not my last, Agatha Christie book, and I truly loved it!. It was a wonderful mystery that kept me guessing the whole way through. I really liked the structure of the novel. Each character getting their own chapter was a genius idea, it really helped me to get to know them. All of them seemed realistic and well developed, which was surprising, considering the amount of people and the rather short length of the book. The writing style was very atmospheric and enjoyable to read. It matched the genre perfectly.',
		},
		cover:
			'https://www.thevintagenews.com/wp-content/uploads/2017/09/9780062838629-424x640.jpg',
		url: 'https://www.amazon.in/Murder-Orient-Express-Poirot-Christie/dp/0007527500/ref=sr_1_2?crid=7INKTRGNNRZC&keywords=Murder+on+the+Orient+Express&qid=1697366221&sprefix=murder+on+the+orient+express%2Caps%2C235&sr=8-2',
		price: 281,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Carlie',
			body: '"I have in my heart of hearts a favourite child. And his name is DAVID COPPERFIELD"\nI have also a favorite author and his name is Charles Dickens.This novel is poetry. To truly appreciate the beauty of the English language, one must read David Copperfield. This book cannot be classified. It is a love story, a drama, and a comedy. It has elements of horror and suspense. I laughed hysterically, sobbed uncontrollably, and threw it to a wall in a fit of anger. It annoyed, bored, and entrapped me.\nThe characters in this novel are like real people to me and I feel for them as I feel for living creatures. I despise Mr. Murdstone, I adore David, I want to slap his mother, I would spit on Dora, I laugh with Peggotty, I cheer Emily on, I pity Uriah Heep, and I sympathize with his aunt Betsy Trotwood. It was such a memorable experience that more than 15 years later, I can still recall certain scenes as if they were part of my actual memory.\nAll that is good about this world (innocence, justice, truth) can be found within these pages. I cannot reccommend it highly enough.',
		},
		_id: '653fce69bcb135ac0922a0df',
		book_id: 13,
		title: 'David Copperfield',
		pages: 882,
		genres: ['Classics', 'Fiction', 'Literature', 'Novels', 'Historic fiction'],
		rating: 4.03,
		plot: "David Copperfield is the story of a young man's adventures on his journey from an unhappy and impoverished childhood to the discovery of his vocation as a successful novelist. Among the gloriously vivid cast of characters he encounters are his tyrannical stepfather, Mr Murdstone; his brilliant, but ultimately unworthy school-friend James Steerforth; his formidable aunt, Betsey Trotwood; the eternally humble, yet treacherous Uriah Heep; frivolous, enchanting Dora Spenlow; and the magnificently impecunious Wilkins Micawber, one of literature's great comic creations.",
		cover:
			'https://i5.walmartimages.com/asr/56f890e5-b099-460d-b735-f895a92d51ac_1.cc424c493a8888fd7ae0a71e7f607ec7.jpeg',
		url: 'https://www.amazon.in/David-Copperfield-Charles-Dickens/dp/8175994282/ref=sr_1_1_sspa?crid=24G90QDITOB9P&keywords=david+copperfield+by+charles+dickens&qid=1698680273&sprefix=david+copp%2Caps%2C250&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
		__v: 0,
		price: 369,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Kimber',
			body: 'Oh, the beauty and the agony tears at me as I think about this stunning story.\nThe characters are vivid and the settings so well written that I was transported to the graveyard alongside young Pip and his convict, fear streaking through me as it was for that small boy torn by a near-impossible decision. And I’m there with Pip and kind-hearted Joe in the forge. I can feel the fire on my skin and taste hot metal on the back of my tongue. In my mind, I hear the crackling of the decades-old crinoline of Miss Havisham’s skirts rustling against the marble floors of the mausoleum she calls home. Amid the stopping of Miss Havisham’s clock, the cool radiance that is Estella vibrates from the pages, bringing her to life.\nIf you haven’t read Great Expectations, I encourage you to do so. Yes, it was first published in 1861, and the syntax is more eloquent than that we’ve become accustomed to, but once this tale grabs hold, you will forget the language and year it was written and be all in with these new friends. The love, the heartbreak and the lessons still hold true today. Some choices, once made, can leave long-reaching scars on the hearts of those we never knew we touched. A good deed can ripple through time to places never imagined. The consequences of our actions must be accounted for, and there will always be outcomes we could never have anticipated.\nGreat Expectations is the real deal! The deliciously-satisfying prose is the whipped cream on the proverbial sundae that is Dickens. The plot and subplots (and sub-subplots) are astounding! The way he can weave this tangled web yet keep the interest of the reader while giving nothing away until the perfect moment … and BAM! He has you, and you sigh with the perfection of it all.\nYou’ve missed a gorgeous piece of literature if you don’t dive into this book!',
		},
		_id: '65406ef9e3598558b3753169',
		book_id: 14,
		title: 'Great Expectations',
		pages: 608,
		genres: [
			'Classics',
			'Romance',
			'Family-drama',
			'Historic fiction',
			'Fiction',
			'19th Century',
		],
		rating: 3.79,
		plot: 'Great Expectations charts the progress of Pip from childhood through often painful experiences to adulthood, as he moves from the Kent marshes to busy, commercial London, encountering a variety of extraordinary characters ranging from Magwitch, the escaped convict, to Miss Havisham, locked up with her unhappy past and living with her ward, the arrogant, beautiful Estella.\nPip must discover his true self, and his own set of values and priorities. Whether such values allow one to prosper in the complex world of early Victorian England is the major question posed by Great Expectations.',
		cover:
			'https://imgv2-1-f.scribdassets.com/img/word_document/251891517/original/41c439d8f6/1585577396?v=1',
		url: 'https://www.amazon.in/Great-Expectations-Charles-Dickens/dp/8175993782/ref=sr_1_3?crid=2OCJMSL2W8SO&keywords=Great+expectations+by+charles+dickens&qid=1698721104&sprefix=great+expectations+by+charles+dickens%2Caps%2C288&sr=8-3',
		__v: 0,
		price: 239,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Laura',
			body: 'Years of teaching this novel to teenagers never dimmed my thrill in reading it — if anything, I grew to love it more every time I watched kids gasp aloud at the revelations! Critics are divided on its place in the Dickens canon, but the ones who think it an inferior work are simply deranged. It has everything: dark deeds, revolution, madness, love, thwarted love, forgiveness, revenge, and a stunning act of self-sacrifice. And melodrama! Oh, how Dickens loved melodrama, but in A Tale of Two Cities it reaches truly grand proportions.\nIt’s the ultimate mystery novel: characters act strangely, but always for a reason. Miscellaneous people drift in and out, but they’re not truly miscellaneous — you just have to wait to see how they’re connected. And like any good mystery, the payoff at the end is worth the time it takes to get there...and what a payoff! Dickens is a master of the type of narration that simultaneously moves forward and back in time. In other words, strategically placed revelations from the past inform the present and shape the future. The brilliant timing both of his hints and of the actual revelations is a bonus field of study. Merely the drama of the dark past and its impact on the “here and now” story is thrilling enough. Plus, A Tale of Two Cities is a profoundly moral story, with themes of vengeance versus forgiveness, sins of the fathers being visited on the children, resurrection and rebirth, and the possibility of redemption.',
		},
		_id: '65407469e3598558b375316c',
		book_id: 15,
		title: 'A Tale of Two Cities',
		pages: 489,
		genres: [
			'Classics',
			'Historical',
			'Literature',
			'Historic fiction',
			'Fiction',
			'19th Century',
			'School',
		],
		rating: 3.87,
		plot: 'A Tale of Two Cities is Charles Dickens’s great historical novel, set against the violent upheaval of the French Revolution. The most famous and perhaps the most popular of his works, it compresses an event of immense complexity to the scale of a family history, with a cast of characters that includes a bloodthirsty ogress and an antihero as believably flawed as any in modern fiction. Though the least typical of the author’s novels, A Tale of Two Cities still underscores many of his enduring themes—imprisonment, injustice, social anarchy, resurrection, and the renunciation that fosters renewal.',
		cover:
			'https://onlinereadfreenovel.com/i2/1707052207/8328_a_tale_of_two_cities.jpg',
		url: 'https://www.amazon.in/Tale-Two-Cities-Charles-Dickens/dp/8171674070/ref=sr_1_1_sspa?crid=231HTZ2B6MR32&keywords=A+Tale+of+Two+Cities+by+charles+dickens&nsdOptOutParam=true&qid=1698722668&sprefix=a+tale+of+two+cities+by+charles+dickens%2Caps%2C577&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
		__v: 0,
		price: 250,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Margaret',
			body: 'What I loved about this book was the characterisation. Dickens is one of the best at developing his characters to the point the reader can identify with each one, their traits, their flaws and purpose. The Plot and the exposés were probably easy to work out part way through once the enquiries started into Esther, but what you could not foresee is how we arrive at the ending.\nWhilst the writing in some of these great novels may not flow easily for the reader, I find the writing, descriptions, choice of words, and story telling superb. If you sit back and reflect on what you have just read, you can appreciate the sheer brilliance of Dickens. Because “A word in earnest is as good as a speech”.\nIn some cases, Dickens conveys the emotions in other cases he hints at them. In some instances, he will reveal the plot and motive in other cases, he will leave it up to the reader to uncover the message, the connection, and the intention. Dickens is the master of suggestion - with perfectly timed comments, and subtle statements that come back later in the book and prove to be significant to the story.\nI found the disreputable and dishonest characters more fascinating than Esther, a central character, who felt too good, too safe, and more like the poor but angelic little girl. I felt she lacked grit and real substance and felt too good to be true. I enjoy a bit more spice. Although intriguing the story was not sufficiently complex to warrant a book of this length. So it will feel a bit long, unless you just want to savour Dickens writing.\nExcellent and although not my favourite Dickens novel, it is a timeless classic written by the master of character development who captures the immutable truth about human nature - perfectly. An author who writes beautifully, and can mix tragedy with love, honesty with deception but most of all an author who creates the drama and will leave you wanting to read more of his books.\nDickens is so good at penetrating your thoughts, that you find yourself reflecting on his stories, the plot, themes and messages a while after reading. Very memorable, often bleak but timeless.',
		},
		_id: '65407f16e3598558b375316f',
		book_id: 16,
		title: 'Bleak House',
		pages: 1017,
		genres: [
			'Classics',
			'Historical',
			'Literature',
			'Historic fiction',
			'Fiction',
			'19th Century',
			'Mystery',
			'British Literature',
		],
		rating: 4.01,
		plot: "Bleak House opens in the twilight of foggy London, where fog grips the city most densely in the Court of Chancery. The obscure case of Jarndyce and Jarndyce, in which an inheritance is gradually devoured by legal costs, the romance of Esther Summerson and the secrets of her origin, the sleuthing of Detective Inspector Bucket and the fate of Jo the crossing-sweeper, these are some of the lives Dickens invokes to portray London society, rich and poor, as no other novelist has done. Bleak House, in its atmosphere, symbolism and magnificent bleak comedy, is often regarded as the best of Dickens. A 'great Victorian novel', it is so inventive in its competing plots and styles that it eludes interpretation.",
		cover:
			'https://i.pinimg.com/originals/3a/c8/68/3ac8687bc0f5595d49fc0c624a3c659d.jpg',
		url: 'https://www.amazon.in/Bleak-Wordsworth-Classics-Charles-Dickens/dp/1853260827/ref=sr_1_3?crid=2TYCJ7HQLXU9V&keywords=bleak+house+by+charles+dickens&nsdOptOutParam=true&qid=1698723211&sprefix=Bleak++by+charles+dickens%2Caps%2C284&sr=8-3',
		__v: 0,
		price: 249,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Piyangie',
			body: "The original title The Life and Adventures of Nicholas Nickleby pretty well sums up the story. Yes, it is about Nicholas, an honest, trusting, good-natured, and good-hearted youth who is thrown at the mercy of the world with his father's untimely death. With the care of his mother and sister weighing heavily upon him and with no sincere help from his usurer uncle, he struggles to find his way in the world and to raise himself from sheer poverty to respectability.\nNicholas is one interesting hero of Dickens, and quite different from any other Dickensian hero I've come across. He is strong-minded, courageous, and persevering. He is governed by a strong sense of duty and justice. His nature is such that fiercely arouse at injustice, cruelty, and wickedness. At such times, one can say the young hero is impetuous, quick-tempered, and even violent. These contrary character traits make Nicholas one of Dickens's chivalrous and colourful heroes.\nAside from Nicholas, we meet quite an interesting set of characters, both male and female. Of them, some are good, kind, and helpful; some are wicked and greedy; and some silly and vain. Dickens is very fond of using many different characters in his books, and in each of them, he never fails to present the readers with some memorable ones. And Nicholas Nickleby too makes a few contributions to that lot.\nIt was a prevalent idea that Dickens didn't create strong female characters in his early works and that they came only in his later mature ones. But Nicholas Nickleby effectually silences this misconception with Kate Nickleby, Nicholas's brave little sister, who is one strong female character that we'll hold dear.\nNicholas Nickleby shows a marked difference from his later works. This difference stems out more from his style of writing. It is youthful, exuberant, action-packed, and dramatic. It has the usual Dickensian satire but not the depth and gravity that graced his later work. Dickens was himself a youth when he wrote this, so a lot of youthful energy is poured into the story and the character of Nicholas. This style of Dickens which I'm not quite acquainted with was very pleasing. It made the reading light and easy despite his inherent verbosity.\nThis is another great creation of Charles Dickens. Reading it was a fascinating experience. The more I read Dickens, the more I understand why he is revered over the centuries. I never gave much thought to Dickens's position as the most outstanding Victorian author before. But I'm slowly on the way to form the same opinion myself.\n",
		},
		_id: '6549e998bb6ef54f8f7d8eb5',
		book_id: 16,
		title: 'Nicholas Nickleby',
		pages: 817,
		genres: [
			'Classics',
			'Historical',
			'Literature',
			'Historical fiction',
			'Fiction',
			'19th Century',
		],
		rating: 3.93,
		plot: "When Nicholas Nickleby is left penniless after his father's death, he appeals to his wealthy uncle to help him find work and to protect his mother and sister. But Ralph Nickleby proves both hard-hearted and unscrupulous, and Nicholas finds himself forced to make his own way in the world. His adventures gave Dickens the opportunity to portray an extraordinary gallery of rogues and eccentrics: Wackford Squeers, the tyrannical headmaster of Dotheboys Hall, a school for unwanted boys; the slow-witted orphan Smike, rescued by Nicholas; and the gloriously theatrical Mr and Mrs Crummles and their daughter, the 'infant phenonenon'. Like many of Dickens's novels, Nicholas Nickleby is characterised by his outrage at cruelty and social injustice, but it is also a flamboyantly exuberant work, revealing his comic genius at its most unerring.",
		cover: 'https://d2snwnmzyr8jue.cloudfront.net/opr_9781504061605_270.jpeg',
		url: 'https://www.amazon.in/Nicholas-Nickleby-Penguin-Classics-Charles/dp/0140435123/ref=sr_1_2?crid=1ENOO3CF3QNG1&keywords=nicholas+nickleby+by+charles+dickens&qid=1699341011&sprefix=Nicholas+Nickleby%2Caps%2C197&sr=8-2',
		__v: 0,
		price: 385,
	},
	{
		author: {
			first_name: 'Charles',
			last_name: 'Dickens',
			middle_name: 'John Huffman',
		},
		review: {
			name: 'Henry',
			body: 'Now this book is primarily a love story although in a convoluted narrative, containing fraud, murder, suicide and hate, domestic violence...plenty of that, mystery, weird noises in a dilapidated mansion, the lopsided shaped edifice, inside an old recluse woman with bitter memories and a son which he and her the mother, dislike each other stating it mildly.... A evil man who likes doing evil things, however some think this is a comedy ....to each their own. Arthur Clennam the son after twenty years in China working with the recently deceased father in business comes home at the age of forty a virtual stranger in his native land of England...And the people old friends and particularly relatives unknown, they in reality are strangers . Mother, Mrs. Clennam cold, intelligent, unforgiving lady with dark secrets in a wheelchair for many years...her eyes show hatred and Mr.Clennam wonders why ? The parents were for a numerous time, estranged. In the same house a poor little woman of 22, Amy Dorrit a part time servant there that for obvious reasons Arthur calls "Little Dorrit," the timid girl doesn\'t mind...Her father William has been in debtors prison, Marshalsea for 23 years... still the amenable man becomes the leader of the inmates, surviving by accepting small gifts from the unlucky creatures, the poor giving to the poorer . But of course his daughter Amy lives with him in the ugly compound taking care of the wretch, the widower two other children envious Fanny , and Edward the drunk have shed the bad remembrances or tried to and live outside, not very well though. Arthur falls for Amy but being 18 years older is he entitled, feeling uncomfortable and sees various women, Flora a lady he almost married but the flame is out only Little Dorrit can lite . Starting a new business with Daniel Doyce a brilliant inventor lacking the ways of bookkeeping they are perfect until the troubles begin; money or not enough as it is everywhere. However the wealthiest man in England all say Mr. Merdle, has a get- rich- quick business proposition, Arthur is tempted. Then Mr.Blandois, not his real name for sure he has many, the evil man mentioned before, reenters the scene bringing gloom and destruction for those unable or unwilling to pay up, a mustached villain with a pointed nose the very image of mid 19th century, blackmail is his game. To anyone who has read Mr. Dickens will surmise the ending but the fun is taking the long log (obstacles ) road getting there. Little Dorrit is such a lovable girl which any person with a heart will love. The bad thing is they only exist in fiction.',
		},
		_id: '6549ebd1bb6ef54f8f7d8eb8',
		book_id: 17,
		title: 'Little Dorrit',
		pages: 1021,
		genres: [
			'Classics',
			'Historical',
			'Literature',
			'Historical fiction',
			'Fiction',
			'19th Century',
			'Romance',
			'Victorian',
		],
		rating: 4,
		plot: "When Arthur Clennam returns to England after many years abroad, he takes a kindly interest in Amy Dorrit, his mother's seamstress, and in the affairs of Amy's father, William Dorrit, a man of shabby grandeur, long imprisoned for debt in Marshalsea prison. As Arthur soon discovers, the dark shadow of the prison stretches far beyond its walls to affect the lives of many, from the kindly Mr Panks, the reluctant rent-collector of Bleeding Heart Yard, and the tipsily garrulous Flora Finching, to Merdle, an unscrupulous financier, and the bureaucratic Barnacles in the Circumlocution Office. A masterly evocation of the state and psychology of imprisonment, Little Dorrit is one of the supreme works of Dickens's maturity.",
		cover:
			'https://th.bing.com/th/id/OIP.WOgV2sUeO_lUGQ2BIQOW3AHaLX?pid=ImgDet&rs=1',
		url: 'https://www.amazon.in/Little-Wordsworth-Classics-Charles-Dickens/dp/1853261823/ref=sr_1_2?crid=T0RX2PUQ5KT6&keywords=Little+Dorrit+by+charles+dickens&qid=1699342782&sprefix=little+dorrit+by+charles+dickens%2Caps%2C288&sr=8-2',
		__v: 0,
		price: 249,
	},
	{
		author: {
			first_name: 'George',
			last_name: 'Eliot',
			middle_name: '',
		},
		review: {
			name: 'Beccie',
			body: "I believe this may be the most beautiful book I have ever read. I felt both uplifted and emotionally drained when I finished. The tragedy and the great beauty of George Eliot's writing! I didn't read this edition, mine was much older, but the introduction of my edition quoted Charles Dickens as saying that reading Adam Bede was an epoch in his life, and Alexandre Dumas called it the masterpiece of the century. I'm happy to agree with them. Most people say that Middlemarch is George Eliot's masterpiece. That was tragic and beautiful as well, but I was so much more drawn into the characters of Adam Bede. I loved them all (even Hetty) because even though they may have made bad choices, we were allowed to see things from their perspective and gain an understanding of why they did what they did. I love that about George Eliot. Dickens' characters sometimes seem almost like caricatures because they are either so good or so evil. I appreciate the humanity of Eliot. In fact, I understood Arthur Donnithorne all too well. He so wants to be a good person and have people think well of him, and yet he is weak when it really matters. This is a silly analogy, but I decided to make chocolate chip cookies one day while reading Adam Bede. I knew I really shouldn't because I would eat too many and not be able to stop, but when it came to the point I made them anyway and ate too many. I realized how like Arthur that was! He knew he shouldn't be doing what he was doing, and he talked himself out of it many times, but when it came to the point he still did it.\nIt's interesting that although George Eliot personally seemed to have issues with the religion of her day, she can talk about religion so beautifully in her books. (I realize I have used the word \"beautiful\" way too many times, but oh if you read it, you will understand.) The year the story takes place is 1799, but the year it was published was (I believe) 1856. There was a lot of religious fervor going on at that time. People were searching and wanting to do what was right, and were dissatisfied with the nation's religion, even though there were many good and wonderful members of the clergy. Who could not love Mr. Irwine? And yet Dinah believed in so much more. I had ancestors in England around that time period who I believe felt the same way, and that's why they were so open to hear of the restoration of the gospel from the Mormon missionaries who were sent there.\nMrs. Poyser was an absolute gem! I loved that she was able to tell off the Squire and hold her own with the woman-hating Mr. Massey (I wanted to tell him off, too - I wish we could have heard why he hated women so much.). I was grateful that George Eliot put in an epilogue so we could see what happened to the characters who were missing at the end of the book. This is an amazing book - everyone should read it.",
		},
		_id: '6549fa51bb6ef54f8f7d8ecb',
		book_id: 18,
		title: 'Adam Bede',
		pages: 624,
		genres: [
			'Classics',
			'Historical fiction',
			'Literature',
			'Romance',
			'Fiction',
			'19th Century',
			'Victorian',
		],
		rating: 3.81,
		plot: 'Adam Bede, a local carpenter admired for his integrity and intelligence. Hetty Sorrel, a beautiful but self-absorbed young woman. Captain Arthur Donnithorne, the charming young squire who seduces Hetty. Dinah Morris, Hetty’s cousin, a fervent, virtuous Methodist lay preacher.\nAdam secretly loves Hetty, but she is drawn to Captain Donnithorne. Hetty falls in love with Arthur, the local squire’s grandson. When Adam interrupts a tryst between Hetty and Arthur, they fight. Arthur agrees to give up Hetty and leaves Hayslope.',
		cover: 'https://pictures.abebooks.com/isbn/9780451525277-us-300.jpg',
		url: 'https://www.amazon.in/Adam-Penguin-Classics-George-Eliot/dp/0140436642/ref=sr_1_3?crid=1QI0Z7I3CLI6Y&keywords=Adam+Bede&qid=1699346071&sprefix=adam+bede+%2Caps%2C201&sr=8-3',
		__v: 0,
		price: 490,
	},
	{
		author: {
			first_name: 'William',
			last_name: 'Golding',
			middle_name: 'Gerald',
		},
		review: {
			name: 'Nancy',
			body: "Lord of the Flies is one of the most disturbing books I've ever read. It was required high school reading and since then, I've read it four more times. It is as disturbing now as it was then. Using a group of innocent schoolboys stranded on an island, the author very realistically portrays human behavior in an environment where civilization no longer has meaning.",
		},
		_id: '654a1abeaceafbe13e8ec15f',
		book_id: 19,
		title: 'Lord of the Flies',
		pages: 182,
		genres: [
			'Classics',
			'Fiction',
			'Dystopia',
			'Young Adult',
			'Adventure',
			'High School',
		],
		rating: 3.69,
		plot: 'At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate; this far from civilization the boys can do anything they want. Anything. They attempt to forge their own society, failing, however, in the face of terror, sin and evil. And as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far from reality as the hope of being rescued. Labeled a parable, an allegory, a myth, a morality tale, a parody, a political treatise, even a vision of the apocalypse, Lord of the Flies is perhaps our most memorable novel about “the end of innocence, the darkness of man’s heart.”',
		cover:
			'https://static01.nyt.com/images/2016/10/30/books/review/30LOWRY-CRITICSTAKE/30LOWRY-CRITICSTAKE-articleLarge-v2.jpg?quality=75&auto=webp&disable=upscale',
		url: 'https://www.amazon.in/Flies-Penguin-Classics-Deluxe-editions/dp/0143129406/ref=sr_1_2?crid=1N119YBO0NS8K&keywords=Lord+of+the+Flies&qid=1699354803&sprefix=lord+of+the+flies%2Caps%2C220&sr=8-2',
		__v: 0,
		price: 570,
	},
	{
		author: {
			first_name: 'William',
			last_name: 'Golding',
			middle_name: 'Gerald',
		},
		review: {
			name: 'Jan',
			body: "This might be the finest historical fiction that I have read to date - partly because it works through atmosphere rather than detail.\nThe book is short and the story simple. Set in medieval England during the reign of Henry II it concerns a new Dean who seeks to have a spire built on his cathedral against advice to the contrary and what results from this.\nThe transformation of a cathedral into a medieval building site may not sound terribly exciting but it works through atmosphere and the confusion of motivations.\nThroughout the Dean's language is centred on glorifying the cathedral, but as the novel progresses it is clear that his motivations are more confused and complex. At one moment the Dean has a vision of his spire reaching up into the heavens casting an ever longer shadow across the countryside. Visible from further and further afield more distant travellers and traders turn their feet towards his cathedral. He sees the routes and roads shift to centre on to his town as the new spire becomes a major landmark.\nAs the book ends there is a properly medieval reveal which clarifies the Dean's drive and the opposition to him.",
		},
		_id: '654a23f3aceafbe13e8ec16b',
		book_id: 20,
		title: 'The Spire',
		pages: 272,
		genres: [
			'Classics',
			'Fiction',
			'Religion',
			'Historical Fiction',
			'Literary Fiction',
			'Historical',
		],
		rating: 3.5,
		plot: "Dean Jocelin has a vision: that God has chosen him to erect a great spire on his cathedral. His mason anxiously advises against it, for the old cathedral was built without foundations. Nevertheless, the spire rises octagon upon octagon, pinnacle by pinnacle, until the stone pillars shriek and the ground beneath it swims. Its shadow falls ever darker on the world below, and on Dean Jocelin in particular.\nThe Spire is a dark and powerful portrait of one man's will, and the folly that he creates.",
		cover: 'https://covers.openlibrary.org/b/id/6937489-L.jpg',
		url: 'https://www.amazon.in/Spire-William-Golding/dp/0571362338/ref=sr_1_2?crid=1HN0I2ZANZXQ1&keywords=The+Spire+book+by+william+golding&qid=1699357027&sprefix=the+spire+book+by+william+golding%2Caps%2C191&sr=8-2',
		__v: 0,
		price: 380,
	},
];
